#include <config.h>
#include <stdio.h>
#include <float.h>
#include <stddef.h>
#include <stdint.h>
#include <stdlib.h>
#include <string.h>
#include "macros.h"
#include <stddef.h>
#include "test-snprintf-posix.h"
