#include <config.h>
#include "unicasemap.h"
#include <errno.h>
#include <stdbool.h>
#include <stdlib.h>
#include "unistr.h"
#include "unictype.h"
#include "uninorm.h"
#include "caseprop.h"
#include "context.h"
#include "special-casing.h"
#include "u-casemap.h"
