#include <stdio.h>
#include <stdlib.h>
#include <stddef.h>
#include "fw/src/mgos_debug.h"
#include "fw/src/mgos_debug_hal.h"
#include "common/cs_dbg.h"
#include "mongoose/mongoose.h"
#include "fw/src/mgos_features.h"
#include "fw/src/mgos_hal.h"
#include "fw/src/mgos_hooks.h"
#include "fw/src/mgos_sys_config.h"
#include "fw/src/mgos_uart.h"
