#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/time.h>
#include "common/platforms/esp8266/esp_missing_includes.h"
#include "common/umm_malloc/umm_malloc.h"
#include "esp_system.h"
#include "user_interface.h"
#include "fw/src/mgos_hal.h"
#include "fw/platforms/esp8266/src/esp_features.h"
