#include <config.h>
#include <stdbool.h>
#include <stdio.h>
#include <unistd.h>
#include <stdlib.h>
#include <sys/types.h>
#include <sys/stat.h>
#include <ctype.h>
#include <errno.h>
#include <string.h>
#include <limits.h>
#include "same.h"
#include "dirname.h"
#include "error.h"
#include "same-inode.h"
