#include <config.h>
#include <sys/types.h>
#include <sys/stat.h>
#include "sys/stat.h"
#include <errno.h>
#include <limits.h>
#include <stdbool.h>
#include <string.h>
#include "dosname.h"
#include "verify.h"
