#include <config.h>
#include <stddef.h>
#include <fcntl.h>
#include <sys/types.h>
#include "fcntl.h"
#include <errno.h>
#include <stdarg.h>
#include <string.h>
#include <sys/types.h>
#include <sys/stat.h>
#include <unistd.h>
