#include <stdio.h>
#include "app.h"
#include "peripheral/peripheral.h"
#include "pic32_uart.h"
#include "pic32_ethernet.h"
#include "common/cs_dbg.h"
#include "fw/src/mgos_init.h"
#include "fw/src/mgos_mongoose.h"
#include "fw/src/mgos_sys_config.h"
