#include <config.h>
#include "mgetgroups.h"
#include <stdlib.h>
#include <unistd.h>
#include <stdint.h>
#include <string.h>
#include <errno.h>
#include <stddef.h>
#include "getugroups.h"
#include "xalloc-oversized.h"
