#include <config.h>
#include "areadlink.h"
#include <fcntl.h>
#include <errno.h>
#include <stdbool.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/stat.h>
#include <unistd.h>
#include "ignore-value.h"
#include "macros.h"
#include "test-areadlink.h"
