#include <config.h>
#include "unistdio.h"
#include <errno.h>
#include <stdarg.h>
#include <stddef.h>
#include <stdint.h>
#include <stdlib.h>
#include <string.h>
#include "unistr.h"
#include "macros.h"
#include "test-u8-printf1.h"
