#include <config.h>
#include <stddef.h>
#include <stddef.h>
#include "uniwbrk.h"
#include <string.h>
#include "unistr.h"
#include "uniwbrk/wbrktable.h"
#include "u-wordbreaks.h"
#include <stdio.h>
#include <stdlib.h>
