#include <config.h>
#include "uniwbrk.h"
#include <stdlib.h>
#include <string.h>
#include "c-ctype.h"
#include "localcharset.h"
#include "uniconv.h"
#include "unilbrk/ulc-common.h"
#include <locale.h>
#include <stdio.h>
#include <stdlib.h>
